/**
 * Autogenerated by Postman CLI (postman mock generate)
 */
const http = require('http');
const PORT = process.env.PORT || 4010;

const server = http.createServer((req, res) => {
  const url = new URL(req.url || '', 'http://localhost');
  const pathname = url.pathname;

  // @endpoint GET /api/health
  if (req.method === 'GET' && pathname === '/api/health') {
    const requestedStatusCode = req.headers['x-mock-response-code'];

    // "An unexpected failure inside a handler. The router catches every `RuntimeException` and returns this rather than letting a stack trace reach the client, so the body is always the generic message below." — when x-mock-response-code: 500
    if (requestedStatusCode === '500') {
      res.writeHead(500, {"Content-Type":"application/json"});
      return res.end(JSON.stringify({"status":500,"error":"Internal error"}));
    }

    // "Service is up." — default
    res.writeHead(200, {"Content-Type":"application/json"});
    return res.end(JSON.stringify({"status":"ok","service":"kiga3000","api":"read-only"}));
  }

  // @endpoint GET /api/cards
  if (req.method === 'GET' && pathname === '/api/cards') {
    const requestedStatusCode = req.headers['x-mock-response-code'];

    // "An unexpected failure inside a handler. The router catches every `RuntimeException` and returns this rather than letting a stack trace reach the client, so the body is always the generic message below." — when x-mock-response-code: 500
    if (requestedStatusCode === '500') {
      res.writeHead(500, {"Content-Type":"application/json"});
      return res.end(JSON.stringify({"status":500,"error":"Internal error"}));
    }

    // "All card summaries. Empty array if the index holds no cards." — default
    res.writeHead(200, {"Content-Type":"application/json"});
    return res.end(JSON.stringify([{"id":1,"gruppe":1,"vorname":"Anna","nachname":"Musterkind","geburtsdatum":"11.03.2020","eintritt":"01.09.2023"},{"id":2,"gruppe":1,"vorname":"Ben","nachname":"Beispiel","geburtsdatum":"20.11.2020","eintritt":"01.09.2023"}]));
  }

  // @endpoint POST /api/cards
  if (req.method === 'POST' && pathname === '/api/cards') {
    res.writeHead(405, {"Allow":"GET","Content-Type":"application/json"});
    return res.end(JSON.stringify({"status":405,"error":"This API is read-only"}));
  }

  // @endpoint GET /api/cards/:id
  if (req.method === 'GET' && /^\/api\/cards\/([^/]+)$/.test(pathname)) {
    const requestedStatusCode = req.headers['x-mock-response-code'];

    // "The `id` path segment is not an integer." — when x-mock-response-code: 400
    if (requestedStatusCode === '400') {
      res.writeHead(400, {"Content-Type":"application/json"});
      return res.end(JSON.stringify({"status":400,"error":"Not a number: For input string: \"abc\""}));
    }

    // "No card exists with that id." — when x-mock-response-code: 404
    if (requestedStatusCode === '404') {
      res.writeHead(404, {"Content-Type":"application/json"});
      return res.end(JSON.stringify({"status":404,"error":"No card with id 99999"}));
    }

    // "An unexpected failure inside a handler. The router catches every `RuntimeException` and returns this rather than letting a stack trace reach the client, so the body is always the generic message below." — when x-mock-response-code: 500
    if (requestedStatusCode === '500') {
      res.writeHead(500, {"Content-Type":"application/json"});
      return res.end(JSON.stringify({"status":500,"error":"Internal error"}));
    }

    // "The card summary." — default
    res.writeHead(200, {"Content-Type":"application/json"});
    return res.end(JSON.stringify({"id":12,"gruppe":2,"vorname":"Elias","nachname":"Roßberg","geburtsdatum":"08.02.2019","eintritt":"01.09.2022"}));
  }

  // @endpoint GET /api/groups/:gruppe/cards
  if (req.method === 'GET' && /^\/api\/groups\/([^/]+)\/cards$/.test(pathname)) {
    const requestedStatusCode = req.headers['x-mock-response-code'];

    // "The `gruppe` path segment is not an integer." — when x-mock-response-code: 400
    if (requestedStatusCode === '400') {
      res.writeHead(400, {"Content-Type":"application/json"});
      return res.end(JSON.stringify({"status":400,"error":"Not a number: For input string: \"abc\""}));
    }

    // "The group number is outside the supported range `0..255`." — when x-mock-response-code: 404
    if (requestedStatusCode === '404') {
      res.writeHead(404, {"Content-Type":"application/json"});
      return res.end(JSON.stringify({"status":404,"error":"No such group: 300"}));
    }

    // "An unexpected failure inside a handler. The router catches every `RuntimeException` and returns this rather than letting a stack trace reach the client, so the body is always the generic message below." — when x-mock-response-code: 500
    if (requestedStatusCode === '500') {
      res.writeHead(500, {"Content-Type":"application/json"});
      return res.end(JSON.stringify({"status":500,"error":"Internal error"}));
    }

    // "Card summaries in the group. Empty array if the group exists in range but holds no cards." — default
    res.writeHead(200, {"Content-Type":"application/json"});
    return res.end(JSON.stringify([{"id":16,"gruppe":3,"vorname":"Amelie","nachname":"Vogtländer","geburtsdatum":"06.05.2018","eintritt":"01.09.2021"}]));
  }

  res.writeHead(404, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify({ error: 'Endpoint not defined' }));
});

server.listen(PORT);
